### ISSUE TITLE
Low memory option

### ISSUE THREAD

**Issue by lskatz** [lskatz/dists2trees#2]
Find a way to do format conversion with lower memory. 

Ideas:
* Try to find if someone else has a more efficient conversion somewhere else in the world
* Use BerkeleyDB to take advantage of disk instead of memory

**Comment by lskatz** [comment]
CC @mbhall88

**Comment by mbhall88** [comment]
I mean it should be possible to convert a square matrix to phylip without keeping both matrices in memory right? Read the first line, which is sample (taxon) names, then each line after that is essentially a row in the phylip right?

**Comment by lskatz** [comment]
I think you're right. I can add a special case when converting matrix to tsv so that it only has to read one line at a time. However, that would require maybe two passes: 1) find the number of taxa because phylip requires that count at the top and also to make sure that the row and column order matches and then 2) copy over the values. I'll see what I can cook up.

**Comment by lskatz** [comment]
I haven't tested it on large files yet but I did the two pass method. It makes a compressed temporary file in TMPDIR that contains all the phylip, except the numsamples field. Then it streams correct phylip to stdout including the numsamples.

**Comment by mbhall88** [comment]
Can you not get the number of taxa from the first line in the matrix?

**Comment by lskatz** [comment]
> Can you not get the number of taxa from the first line in the matrix?

Dangit why didn't I think of that
